Comment out submodule update and status steps
Commented out the submodule update and status setting steps in the auto_build workflow.

diff --git a/.github/workflows/auto_build.yml b/.github/workflows/auto_build.yml
--- a/.github/workflows/auto_build.yml
+++ b/.github/workflows/auto_build.yml
@@ -24,28 +24,27 @@ jobs:
           token: ${{ secrets.YOUSSEF_RUNNER }}
           fetch-depth: 0
 
-      - name: Update submodule to PR commit
-        run: |
-            $SubmoduleName = "${{ github.event.client_payload.repo_name }}"
-            $SubmoduleStatus = git submodule status
-            $SubmodulePath = $SubmoduleStatus.Split(" ")[2]
+      # - name: Update submodule to PR commit
+      #   run: |
+      #       $SubmoduleName = "${{ github.event.client_payload.repo_name }}"
+      #       $SubmoduleStatus = git submodule status
+      #       $SubmodulePath = $SubmoduleStatus.Split(" ")[2]
             
-            if ($SubmodulePath) {
-                Write-Output "Submodule '$SubmoduleName' is located at: $SubmodulePath"
-            } else {
-                Write-Error "Submodule '$SubmoduleName' not found!"
-                exit 1
-            }
-            cd $SubmodulePath
-            git fetch origin
-            git checkout -b branch_name --track origin/branch_name/${{ github.event.client_payload.branch_name }}
+      #       if ($SubmodulePath) {
+      #           Write-Output "Submodule '$SubmoduleName' is located at: $SubmodulePath"
+      #       } else {
+      #           Write-Error "Submodule '$SubmoduleName' not found!"
+      #           exit 1
+      #       }
+      #       cd $SubmodulePath
+      #       git fetch origin
+      #       git checkout -b branch_name --track origin/branch_name/${{ github.event.client_payload.branch_name }}
 
       - name: Run script
         id: run-script-1
         run: |
           echo %CD%
-          cd .\application\sub_modd_test
-          .\example1.bat
+          echo youssef
 
       # - name: Run script 1
       #   id: run-script-2
@@ -60,24 +59,24 @@ jobs:
       #     cd .\application\sub_modd_test
       #     .\example1.bat
 
-      - name: Set status on submodule PR
-        if: always()  # Runs even if previous steps fail
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.YOUSSEF_RUNNER }}
-          script: |
-            const outcomes = [
-              '${{ steps.run-script-1.outcome }}',
-            ];
-            const state = outcomes.every(outcome => outcome === 'success') ? 'success' : 'failure';
-            const description = state === 'success' ? 'All scripts ran successfully' : 'One or more scripts failed';
-            await github.rest.repos.createCommitStatus({
-              owner: 'YoussefHeshamSalah',
-              repo: '${{ github.event.client_payload.repo_name }}',
-              sha: '${{ github.event.client_payload.sha_num }}',
-              state: state,
-              context: 'main-repo-check',
-              description: description,
-              target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
-            });
+      # - name: Set status on submodule PR
+      #   if: always()  # Runs even if previous steps fail
+      #   uses: actions/github-script@v6
+      #   with:
+      #     github-token: ${{ secrets.YOUSSEF_RUNNER }}
+      #     script: |
+      #       const outcomes = [
+      #         '${{ steps.run-script-1.outcome }}',
+      #       ];
+      #       const state = outcomes.every(outcome => outcome === 'success') ? 'success' : 'failure';
+      #       const description = state === 'success' ? 'All scripts ran successfully' : 'One or more scripts failed';
+      #       await github.rest.repos.createCommitStatus({
+      #         owner: 'YoussefHeshamSalah',
+      #         repo: '${{ github.event.client_payload.repo_name }}',
+      #         sha: '${{ github.event.client_payload.sha_num }}',
+      #         state: state,
+      #         context: 'main-repo-check',
+      #         description: description,
+      #         target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
+      #       });
 
